//
//  Bolton.swift
//  UGANutrition
//
//  Created by Lakshay Sharma on 10/20/16.
//  Copyright © 2016 Lakshay Sharma. All rights reserved.
//

import Foundation

class Bolton {
    
    static let bagels = [[
        "sugars-dv": " ",
        "cholesterol-dv": " ",
        "ingredients": "Everything Bagel (INGREDIENTS: UNBLEACHED WHEAT FLOUR (MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, SUGAR, CONTAINS LESS THAN 2% OR LESS OF: SESAME SEEDS, SALT, POPPY SEEDS, ONIONS, GARLIC , YEAST, MOLASSES, SOYBEAN OIL, CALCIUM PROPIONATE (MOLD INHIBITOR), PALM OIL, MONOGLYCERIDES, CORNMEAL, L-CYSTEINE, ASCORBIC ACID, ENZYMES.  **all bagels are made on shared equipment with egg and milk products**)",
        "sodium-dv": "38%",
        "cholesterol": "0mg",
        "trans-fat-dv": " ",
        "serving-name": "Bagel, Everything",
        "trans-fat": "0g",
        "sat-fat": "0.5g",
        "total-carb-dv": "53%",
        "dietary-fiber-dv": "8%",
        "calories-from-fat": "32",
        "total-fat": "3.5g",
        "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
        "total-carb": "69g",
        "sugars": "5g",
        "protein-dv": "23%",
        "serving-size": "1 each",
        "total-fat-dv": " ",
        "calories": "360",
        "protein": "13g",
        "sat-fat-dv": " ",
        "dietary-fiber": "3g",
        "sodium": "880mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "French Toast Bagel (INGREDIENTS: UNBLEACHED UNBROMATED  ENRICHED WHEAT FLOUR (MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, MAPLE BITS (SUGAR,  WHEAT FLOUR, CORN CEREAL, NATURAL FLAVOR, SOYBEAN OIL, FRUCTOSE), CONTAINS 2% OR LESS: SUGAR, SALT, YEAST, CINNAMON, CORN MEAL, NATURAL  AND ARTIFICIAL FLAVORS, CALCIUM PROPIONATE (USED AS A PRESERVATIVE), PALM OIL, MONOGLYCERIDES, DATEM, MOLASSES, SOYBEAN OIL, L-CYSTEINE, ASCORBIC ACID, ENZYMES. **all bagels are made on shared equipment with egg and milk products**)",
                    "sodium-dv": "34%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bagel, French Toast",
                    "trans-fat": "0g",
                    "sat-fat": "0.5g",
                    "total-carb-dv": "60%",
                    "dietary-fiber-dv": "8%",
                    "calories-from-fat": "18",
                    "total-fat": "2g",
                    "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                    "total-carb": "78g",
                    "sugars": "6g",
                    "protein-dv": "25%",
                    "serving-size": "1 each",
                    "total-fat-dv": " ",
                    "calories": "380",
                    "protein": "14g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "3g",
                    "sodium": "780mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Plain Bagel (INGREDIENTS: UNBLEACHED WHEAT FLOUR (MALTED BARLEY, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, SUGAR, CONTAINS 2% OF LESS OF SALT, YEAST, MOLASSES, SOYBEAN OIL, CALCIUM PROPIONATE (A MOLD INHIBITOR), PALM OIL, MONOGLYCERIDES, CORNMEAL, L-CYSTEINE, ASCORBIC ACID, ENZYMES **Produced in a facility that also processes soy, eggs, and tree nuts**products**)",
                    "sodium-dv": "29%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bagel, Plain",
                    "trans-fat": "0g",
                    "sat-fat": "0.5g",
                    "total-carb-dv": "54%",
                    "dietary-fiber-dv": "5%",
                    "calories-from-fat": "14",
                    "total-fat": "1.5g",
                    "allergens": "Milk, Eggs, Tree Nuts, Wheat, Soybeans, Gluten",
                    "total-carb": "70g",
                    "sugars": "5g",
                    "protein-dv": "23%",
                    "serving-size": "1 each",
                    "total-fat-dv": " ",
                    "calories": "340",
                    "protein": "13g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "2g",
                    "sodium": "670mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Very Berry Bagel (INGREDIENTS: UNBLEACHED UNBROMATED ENRICHED WHEAT FLOUR (MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, CONTAINS 2% OR LESS: SUGAR, SALT, CRANBERRY BITS (SUGAR, CORN SYRUP, CORN CEREAL, MODIFIED FOOD STARCH, PARTIALLY HYDROGENATED VEGETABLE OIL (COTTONSEED AND/OR SOYBEAN), CITRIC ACID, ARTIFICIAL FLAVOR, RED #40 LAKE, BLUE #1 LAKE),  CHERRY BITS (SUGAR, CORN SYRUP, CORN CEREAL, PARTIALLY HYDROGENATED VEGETABLE OIL (COTTONSEED AND/OR SOYBEAN), MODIFIED FOOD STARCH, ARTIFICIAL FLAVOR, RED #40), BLUEBERRY BITS (SUGAR, CORN FLOUR, DEXTROSE, CORN STARCH, DRIED BLUEBERRIES, BLUE #40 LAKE, RED #40 LAKE), YEAST, CORN MEAL, NATURAL AND ARTIFICIAL FLAVOR, CALCIUM PROPIONATE (USED AS A PRESERVATIVE), PALM OIL, MONOGLYCERIDES, DATEM, MOLASSES, SOYBEAN OIL, L-CYSTEINE, ASCORBIC ACID, ENZYMES, NATURAL AND ARTIFICIAL COLOR. **all bagels are made on shared equipment with egg and milk products**)",
                    "sodium-dv": "34%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bagel, Very Berry",
                    "trans-fat": "0g",
                    "sat-fat": "1g",
                    "total-carb-dv": "60%",
                    "dietary-fiber-dv": "8%",
                    "calories-from-fat": "18",
                    "total-fat": "2g",
                    "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                    "total-carb": "78g",
                    "sugars": "6g",
                    "protein-dv": "25%",
                    "serving-size": "1 each",
                    "total-fat-dv": " ",
                    "calories": "380",
                    "protein": "14g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "3g",
                    "sodium": "790mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Wheat & Oat Bagel (INGREDIENTS: UNBLEACHED WHEAT FLOUR (MALTED BARLEY FLOUR, NIACIN, REDUCE IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, OATS, WHEAT BRAN, AUGAR, SALT, YEAST, MOLASSES, SOYBEAN OIL, CALCIUM PROPIONATE (USED AS A PRESERVATIVE), PALM OIL, MONOGLYCERIDES, CORNMEAL, L-CYSTEINE, ASCORBIC ACID, ENZYMES. **all bagels are made on shared equipment with egg and milk products**)",
                    "sodium-dv": "29%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bagel, Wheat Bran And Oats",
                    "trans-fat": "0g",
                    "sat-fat": "0.5g",
                    "total-carb-dv": "58%",
                    "dietary-fiber-dv": "18%",
                    "calories-from-fat": "23",
                    "total-fat": "2.5g",
                    "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                    "total-carb": "75g",
                    "sugars": "3g",
                    "protein-dv": "27%",
                    "serving-size": "1 each",
                    "total-fat-dv": " ",
                    "calories": "370",
                    "protein": "15g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "7g",
                    "sodium": "670mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Cinnamon Raisin Swirl Bread (INGREDIENTS: ENRICHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, REDUCED IRON,  THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID) WATER, RAISINS, SUGAR, CINNAMON FLAKES (SUGAR, VEGETABLE OIL [PALM OIL, PALM KERNEL  OIL], CINNAMON, SOY LECITHIN), WHEAT GLUTEN, CONAINS 2% OR LESS OF EACH OF THE FOLLOWING: YEAST, SOYBEAN OIL, SALT, VITAMIN A PALMITATE, CALCIUM CARBONATE, NATURAL FLAVOR, DOUGH CONDITIONERS (CONTAINS ONE OR MORE OF  THE FOLLOWING:  SODIUM STEAROYL LACTYLATE, CALCIUM STEAROYL LACTYLATE,  MONOGLYCERIDES AND/OR DIGLYCERIDES, CALCIUM PEROXIDE, CALCIUM IODATE, DATEM, ETHOXYLATED MONO- AND DIGLYCERIDES, ENZYMES), CINNAMON, CARAMEL COLOR, CULTURED WHEAT FLOUR, VINEGAR, WHEAT STARCH, CHOLECALCIFEROL (VITAMIN D3), CALCIUM SULFATE, SOY LECITHIN, GUAR GUM,  XANTHAN GUM, ALPHA TOCOPHEROL ACETATE (VITAMIN E).)",
                    "sodium-dv": "9%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Cinnamon Raisin",
                    "trans-fat": "0g",
                    "sat-fat": "1g",
                    "total-carb-dv": "23%",
                    "dietary-fiber-dv": "3%",
                    "calories-from-fat": "27",
                    "total-fat": "3g",
                    "allergens": "Wheat, Gluten",
                    "total-carb": "30.4g",
                    "sugars": "12.2g",
                    "protein-dv": "7%",
                    "serving-size": "2 SLICE",
                    "total-fat-dv": " ",
                    "calories": "162",
                    "protein": "4.1g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "1g",
                    "sodium": "202.5mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "English Muffin (INGREDIENTS: UNBLEACHED ENRICHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, YEAST, CORN MEAL, WHEAT GLUTEN, CONTAINS 2% OR LESS OF THE FOLLOWING: CORN FLOUR, SALT, HIGH FRUCTOSE CORN SYRUP, VINEGAR, SOYBEAN OIL, CALCIUM SULFATE, MONOGLYCERIDES, AMMONIUM SULFATE, ASCORBIC ACID, CORN STARCH, ENZYMES, CALCIUM PROPIONATE AND POTASSIUM SORBATE (TO RETARD SPOILAGE). )",
                    "sodium-dv": "12%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, English Muffins",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "18%",
                    "dietary-fiber-dv": "1%",
                    "calories-from-fat": "9",
                    "total-fat": "1g",
                    "allergens": "Wheat, Gluten",
                    "total-carb": "24g",
                    "sugars": "0.5g",
                    "protein-dv": "9%",
                    "serving-size": "1 EA",
                    "total-fat-dv": " ",
                    "calories": "120",
                    "protein": "5g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "0.5g",
                    "sodium": "270mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Gluten Free White Bread (INGREDIENTS: WATER, TAPIOCA STARCH, BROWN RICE FLOUR, CANOLA OIL, EGG WHITES, POTATO STARCH, MODIFIED FOOD STARCH, TAPIOCA MALTODEXTRIN, DRIED CANE SYRUP, TAPIOCA SYRUP, YEAST, GUM (XANTHAN GUM, SODIUM ALGINATE, GUAR GUM), SALT, LOCUST BEAN GUM, CULTURED CORN SYRUP SOLIDS AND CITRIC ACID (MOLD INHIBITOR) ENZYMES.)",
                    "sodium-dv": "17%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Gluten Free White",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "27%",
                    "dietary-fiber-dv": "3%",
                    "calories-from-fat": "54",
                    "total-fat": "5.9g",
                    "allergens": "Eggs",
                    "total-carb": "34.7g",
                    "sugars": "4g",
                    "protein-dv": "11%",
                    "serving-size": "2 SLICE",
                    "total-fat-dv": " ",
                    "calories": "218",
                    "protein": "5.9g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "1g",
                    "sodium": "396.5mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Gluten Free Whole Grain Bread (INGREDIENTS: WATER, TAPIOCA STARCH, BROWN RICE FLOUR, CANOLA OIL, EGG WHITES, POTATO STARCH, DRIED CANE SYRUP, TAPIOCA MALTODEXTRIN, TAPIOCA SYRUP, MODIFIED FOOD STARCH, YEAST, FLAX SEED, SUGARCANE FIBER, SALT, GUM (XANTHAN GUM), SODIUM ALGINATE, GUAR GUM), AMARANTH FLOUR, SORGHUM FLOUR, TEFF FLOUR, LOCUST BEAN GUM, CULTURED BROWN RICE, BROWN RICE, AND ENZYMES. )",
                    "sodium-dv": "19%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Gluten Free Whole Grain",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "28%",
                    "dietary-fiber-dv": "5%",
                    "calories-from-fat": "54",
                    "total-fat": "5.9g",
                    "allergens": "Eggs",
                    "total-carb": "36.7g",
                    "sugars": "4g",
                    "protein-dv": "11%",
                    "serving-size": "2 slice",
                    "total-fat-dv": " ",
                    "calories": "218",
                    "protein": "5.9g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "2g",
                    "sodium": "446.1mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Nature's Own Honey Wheat Bread (INGREDIENTS: UNBLEACHED ENRICHED FLOUR  (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, HONEY, SUGAR, WHEAT GLUTEN, WHOLE WHEAT FLOUR, RYE FLOUR, WHEAT BRAN, CONTAINS 2% OR LESS OF EACH OF THE FOLLOWING: YEAST, SOY FLOUR, SALT, SOYBEAN OIL, MONOGLYCERIDES, ENZYMES, ASCORBIC ACID, CULTURED WHEAT FLOUR, VINEGAR, CALCIUM SULFATE, MONOCALCIUM PHOSPHATE, SOY LECITHIN, CALCIUM CARBONATE.)",
                    "sodium-dv": "10%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Honey Wheat",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "19%",
                    "dietary-fiber-dv": "2%",
                    "calories-from-fat": "17",
                    "total-fat": "1.9g",
                    "allergens": "Wheat, Soybeans, Gluten",
                    "total-carb": "24.3g",
                    "sugars": "3.7g",
                    "protein-dv": "10%",
                    "serving-size": "2 slice",
                    "total-fat-dv": " ",
                    "calories": "131",
                    "protein": "5.6g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "0.9g",
                    "sodium": "233.7mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "100% Whole Wheat Bread (INGREDIENTS: WHOLE WHEAT FLOUR, WATER, SUGAR, WHEAT GLUTEN, YEAST, CRACKED WHEAT, CONTAINS 2% OR LESS OF EACH OF THE FOLLOWING: HONEY, MOLASSES, SALT, SOYBEAN OIL, CULTURED WHEAT FLOUR, VINEGAR, CALCIUM SULFATE, MONOGLYCERIDES, ENZYMES, ASCORBIC ACID, WHEAT STARCH, SOY LECITHIN, CALCIUM CARBONATE, MONOCALCIUM PHOSPHATE, TOPPED WITH CRACKED WHEAT. )",
                    "sodium-dv": "11%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Whole Wheat",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "21%",
                    "dietary-fiber-dv": "10%",
                    "calories-from-fat": "17",
                    "total-fat": "1.8g",
                    "allergens": "Wheat, Gluten",
                    "total-carb": "27.1g",
                    "sugars": "4.9g",
                    "protein-dv": "13%",
                    "serving-size": "2 SLICE",
                    "total-fat-dv": " ",
                    "calories": "136",
                    "protein": "7.4g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "3.7g",
                    "sodium": "246.5mg"
        ]]
    
    
    static let bakery = [[
        "sugars-dv": " ",
        "cholesterol-dv": " ",
        "ingredients": "Andes Mint Pieces (INGREDIENTS: SUGAR, PARTIALLY HYDROGENATED VEGETABLE OILS (PALM KERNEL AND PALM), COCOA (PROCESSED WITH ALKALI), NONFAT MILK, LACTOSE, MILK PROTEIN CONCENTRATE, SOY LECITHIN (AN EMULSIFIER), NATURAL AND ARTIFICIAL FLAVORS, PEPPERMINT OIL, COLORS ADDED (YELLOW 5 LAKE, BLUE 1 LAKE))",
        "sodium-dv": "0%",
        "cholesterol": "0mg",
        "trans-fat-dv": " ",
        "serving-name": "Andes Candies Pieces",
        "trans-fat": "0g",
        "sat-fat": "2.1g",
        "total-carb-dv": "3%",
        "dietary-fiber-dv": "0%",
        "calories-from-fat": "22",
        "total-fat": "2.5g",
        "allergens": "Milk",
        "total-carb": "4.1g",
        "sugars": "3.9g",
        "protein-dv": "1%",
        "serving-size": "1/4 OZ",
        "total-fat-dv": " ",
        "calories": "37",
        "protein": "0.4g",
        "sat-fat-dv": " ",
        "dietary-fiber": "0.1g",
        "sodium": "3.5mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Hot Caramel Topping (INGREDIENTS: CORN SYRUP, HIGH FRUCTOSE CORN SYRUP, SUGAR, CONDENSED NONFAT MILK, HEAVY WHIPPING CREAM, WATER, SALT, PECTIN, ARTIFICIAL FLAVOR, DISODIUM PHOSPHATE )",
                            "sodium-dv": "5%",
                            "cholesterol": "0.7mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Caramel Topping",
                            "trans-fat": "0g",
                            "sat-fat": "0g",
                            "total-carb-dv": "32%",
                            "dietary-fiber-dv": "0%",
                            "calories-from-fat": "6",
                            "total-fat": "0.7g",
                            "allergens": "Milk",
                            "total-carb": "41.5g",
                            "sugars": "30.4g",
                            "protein-dv": "0%",
                            "serving-size": "2 OZ",
                            "total-fat-dv": " ",
                            "calories": "180",
                            "protein": "0g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0g",
                            "sodium": "103.7mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Semi-Sweet Chocolate Chips (INGREDIENTS:SEMI-SWEET CHOCOLATE (SUGAR; CHOCOLATE; COCOA BUTTER; MILK FAT; SOY LECITHIN; VANILLIN, ARTIFICIAL FLAVOR; MILK))",
                            "sodium-dv": "0%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Chocolate Chips, Semi-sweet",
                            "trans-fat": "0g",
                            "sat-fat": "2.4g",
                            "total-carb-dv": "7%",
                            "dietary-fiber-dv": "1%",
                            "calories-from-fat": "34",
                            "total-fat": "3.8g",
                            "allergens": "Milk",
                            "total-carb": "9.5g",
                            "sugars": "7.6g",
                            "protein-dv": "1%",
                            "serving-size": "1/2 OZ",
                            "total-fat-dv": " ",
                            "calories": "66",
                            "protein": "0.5g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0.5g",
                            "sodium": "0mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Hot Fudge Topping (INGREDIENTS: CORN SYRUP, HIGH FRUCTOSE CORN SYRUP, NONFAT MILK, HYDROGENATED COCONUT OIL, WATER, COCOA (PROCESSED WITH ALKALI), WHEY, MODIFIED CORN STARCH, LESS THAN 2% OF: CALCIUM CASEINATE, SALT, POTASSIUM SORBATE (PRESERVATIVE), SODIUM BICARBONATE, ARTIFICIAL FLAVORS, SOY LECITHIN, NATURAL FLAVORS.)",
                            "sodium-dv": "4%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Fudge Topping",
                            "trans-fat": "0g",
                            "sat-fat": "7.1g",
                            "total-carb-dv": "23%",
                            "dietary-fiber-dv": "4%",
                            "calories-from-fat": "71",
                            "total-fat": "7.9g",
                            "allergens": "Milk",
                            "total-carb": "29.9g",
                            "sugars": "20.5g",
                            "protein-dv": "1%",
                            "serving-size": "2 oz",
                            "total-fat-dv": " ",
                            "calories": "205",
                            "protein": "0.8g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "1.6g",
                            "sodium": "86.6mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "M&M Pieces (INGREDIENTS: MILK CHOCOLATE, (SUGAR, CHOCOLATE, SKIM MILK, COCOA BUTTER, LACTOSE, MILKFAT, SOY LECITHIN, SALT, ARTIFICIAL FLAVORS), SUGAR, CORNSTARCH, LESS THAN 1% - CORN SYRUP, DEXTRIN, COLORING (INCLUDES BLUE 1 LAKE, RED 40 LAKE, YELLOW 6, YELLOW 5, RED 40, BLUE 1, BLUE 2 LAKE, YELLOW 6 LAKE, YELLOW 5 LAKE, BLUE 2), GUM ACACIA. **facility may have contact contain peanuts**)",
                            "sodium-dv": "0%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "M&m Pieces",
                            "trans-fat": "0g",
                            "sat-fat": "0.9g",
                            "total-carb-dv": "4%",
                            "dietary-fiber-dv": "0%",
                            "calories-from-fat": "12",
                            "total-fat": "1.3g",
                            "allergens": "Milk, Peanuts",
                            "total-carb": "5g",
                            "sugars": "4.4g",
                            "protein-dv": "1%",
                            "serving-size": "1/4 OZ",
                            "total-fat-dv": " ",
                            "calories": "32",
                            "protein": "0.3g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0.1g",
                            "sodium": "4.4mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Mini Marshmallows (INGREDIENTS: CORN SYRUP, SUGAR, CORN STARCH MODIFIED, WATER, GELATIN, NATURAL AND ARTIFICIAL FLAVOR, TETRASODIUM PYROPHOSPHATE, COLOR (BLUE 1).)",
                            "sodium-dv": "1%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Miniature Marshmallows",
                            "trans-fat": "0g",
                            "sat-fat": "0g",
                            "total-carb-dv": "10%",
                            "dietary-fiber-dv": "0%",
                            "calories-from-fat": "0",
                            "total-fat": "0g",
                            "allergens": " ",
                            "total-carb": "12.5g",
                            "sugars": "10.2g",
                            "protein-dv": "1%",
                            "serving-size": "1/2 OZ",
                            "total-fat-dv": " ",
                            "calories": "51",
                            "protein": "0.3g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0g",
                            "sodium": "14.2mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Oreo Cookie Crumbs  (INGREDIENTS: UNBLEACHED ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE [VITAMIN B1], RIBOFLAVIN [VITAMIN B2], FOLIC ACID), SUGAR, PALM AND/OR CANOLA OIL, COCOA (PROCESSED WITH ALKALI), HIGH FRUCTOSE CORN SYRUP, LEAVENING (BAKING SODA AND/OR CALCIUM PHOSPHATE), CORNSTARCH, SALT, SOY LECITHIN, VANILLIN - AN ARTIFICIAL FLAVOR, CHOCOLATE.)",
                            "sodium-dv": "2%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Oreo Cookie Crumbs",
                            "trans-fat": "0g",
                            "sat-fat": "0.8g",
                            "total-carb-dv": "8%",
                            "dietary-fiber-dv": "1%",
                            "calories-from-fat": "24",
                            "total-fat": "2.6g",
                            "allergens": "Wheat, Soybeans, Gluten",
                            "total-carb": "10.5g",
                            "sugars": "5.8g",
                            "protein-dv": "1%",
                            "serving-size": "1/2 OZ",
                            "total-fat-dv": " ",
                            "calories": "68",
                            "protein": "0.5g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0.3g",
                            "sodium": "55.1mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Whole Milk (INGREDIENTS: MILK, VITAMIN D3.), Chocolate Pudding Mix (INGREDIENTS: SUGAR, FOOD STARCH MODIFIED, COCOA (PROCESSED WITH ALKALI), CALCIUM SULFATE (FOR PROPER SET), TETRASODIUM PYROPHOSPHATE AND DISODIUM PHOSPHATE (STABILIZERS), CONTAINS LESS THAN 2% OF THE FOLLOWING: NATURAL AND ARTIFICIAL FLAVORS, SODIUM ALGINATE (THICKENER), SALT, COTTONSEED OIL, MONO AND DIGLYCERIDES (EMULSIFIERS), RED 40, YELLOW 5, YELLOW 6, BLUE 1, BHT AND TBHQ AND CITRIC ACID ADDED TO PRESERVE FRESHNESS. **manufactured on equipment that process wheat, soy, milk, egg, and tree nuts**)",
                            "sodium-dv": "14%",
                            "cholesterol": "14.6mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Pudding, Chocolate",
                            "trans-fat": "0g",
                            "sat-fat": "2.1g",
                            "total-carb-dv": "17%",
                            "dietary-fiber-dv": "2%",
                            "calories-from-fat": "30",
                            "total-fat": "3.3g",
                            "allergens": "Milk, Eggs, Tree Nuts, Wheat, Soybeans, Gluten",
                            "total-carb": "22.6g",
                            "sugars": "19.8g",
                            "protein-dv": "6%",
                            "serving-size": "4 oz",
                            "total-fat-dv": " ",
                            "calories": "137",
                            "protein": "3.3g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0.9g",
                            "sodium": "329.7mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Whole Milk (INGREDIENTS: MILK, VITAMIN D3.), Vanilla Pudding Mix (INGREDIENTS: SUGAR, FOOD STARCH MODIFIED, YELLOW 5, YELLOW 6, CONTAINS LESS THAN 2% OF THE FOLLOWING: ARTIFICIAL FLAVOR, TETRASODIUM PYROPHOSPHATE AND DISODIUM PHOSPHATE, SODIUM ALGINATE, CALCIUM SULFATE, PALM KERNEL OIL, CORN SYRUP SOLIDS, PROPYLENE GLYCOL, MONOSTARATE, SODIUM CASEINATE, ACETYLATED MONOGLYCERIDES, MONO AND DIGLYCERIDES, CELLULOSE GEL AND CELLULOSE GUM, SALT, SILICON DIOXIDE  **manufactured on equipment that processes wheat, soy, milk, egg, and treenuts)",
                            "sodium-dv": "14%",
                            "cholesterol": "14.6mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Pudding, Vanilla",
                            "trans-fat": "0g",
                            "sat-fat": "2.1g",
                            "total-carb-dv": "18%",
                            "dietary-fiber-dv": "0%",
                            "calories-from-fat": "30",
                            "total-fat": "3.3g",
                            "allergens": "Milk, Eggs, Tree Nuts, Wheat, Soybeans, Gluten",
                            "total-carb": "23.5g",
                            "sugars": "20.7g",
                            "protein-dv": "6%",
                            "serving-size": "4 oz",
                            "total-fat-dv": " ",
                            "calories": "137",
                            "protein": "3.3g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0g",
                            "sodium": "311.2mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Rainbow Sprinkles (INGREDIENTS: SUGAR, GLUCOSE POWDER, CORN STARCH, VEGETABLE FAT, SALT, HUMECTANT GLYCEROL,  EMULSIFIER SOY LECITHIN, GLAZING AGENT TALC, THICKENER GUM ARABIC, NATURAL IDENTICAL FLAVOR, AND FD&C COLORS (BLUE #1, YELLOW #5, RED #40, YELLOW #6 AND RED #3).)",
                            "sodium-dv": "0%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Rainbow Sprinkles",
                            "trans-fat": "0g",
                            "sat-fat": "0.3g",
                            "total-carb-dv": "5%",
                            "dietary-fiber-dv": "0%",
                            "calories-from-fat": "3",
                            "total-fat": "0.3g",
                            "allergens": " ",
                            "total-carb": "6.5g",
                            "sugars": "5.2g",
                            "protein-dv": "0%",
                            "serving-size": "1/4 OZ",
                            "total-fat-dv": " ",
                            "calories": "29",
                            "protein": "0g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0g",
                            "sodium": "2.5mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Cinnamon Red Hots (INGREDIENTS: SUGAR, CORN SYRUP , MODIFIED FOOD STARCH , ARTIFICIAL FLAVOR , GUM ARABIC , CONFECTIONER'S GLAZE , BEESWAX , CARNAUBA WAX , RED NO. 40 )",
                            "sodium-dv": "0%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Red Hots",
                            "trans-fat": " ",
                            "sat-fat": "0g",
                            "total-carb-dv": "5%",
                            "dietary-fiber-dv": "0%",
                            "calories-from-fat": "0",
                            "total-fat": "0g",
                            "allergens": " ",
                            "total-carb": "6.6g",
                            "sugars": "5.7g",
                            "protein-dv": "0%",
                            "serving-size": "1/4 OZ",
                            "total-fat-dv": " ",
                            "calories": "28",
                            "protein": "0g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0g",
                            "sodium": "2.4mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Assorted Danishes (INGREDIENTS: DOUGH (WHEAT FLOUR, MARGARINE [PALM OIL, CANOLA OIL, WATER, MONO & DIGLYCERIDES, SALT, CITRIC ACID, NATURAL FLAVOR, VITAMIN A], WATER, EGG YOLK [EGG YOLK, SALT, YEAST, SUGAR, DOUGH CONDITIONER [DEXTROSE, DATEM, CALCIUM CARBONATE, ENZYMES, ASCORBIC ACID], PECTIN]. MINI SALTED CARAMEL BRAID: FILLING (SUGAR, MARGARINE (PALM OIL, CANOLA OIL, WATER, SALT, MONO AND DIGLYCERIDES), WATER, TOFFEE SYRUP (CORN SYRUP, SUGAR, CONDENSED MILK, BUTTER, MALT SYRUP, BROWN SUGAR, WATER, SALT, MONO AND DIGLYCERIDES), CUSTARD POWDER [SUGAR, MODIFIED POTATO STARCH, WHEY POWDER, NON FAT DRY MILK POWDER, COCONUT OIL, CORN SYRUP, CALCIUM ALGINATE, NATURAL FLAVOR, SALT, MILK PROTEIN, SODIUM PHOSPHATE, SILICON DIOXIDE, CAROTENE (COLOR), WHEAT FLOUR, INVERT SYRUP, THICKENER [ SODIUM ALGINATE, PECTIN, SUCROSE], NATURAL FLAVOR, SEA SALT), TOFFEE PIECES (SUGAR, CORN SYRUP, CONDENSED MILK, PALM OIL, BUTTER, CELLULOSE, NATURAL FLAVOR), READY GLAZE (WATER, ISOMALT, SUGAR, AGAR, POTASSIUM SORBATE, CITRIC ACID) ** Packaged in a container with products that contains almonds** MINI STRAWBERRY SHORTCAKE CROWN: FILLING (STRAWBERRY, SUGAR, WATER, CORNSTARCH, CITRIC ACID, POTASSIUM CITRATE, NATURAL FLAVOR, NATURAL CARROT CONCENTRATE), ALMOND REMONCE (SUGAR, MARGARINE [PALM OIL, CANOLA OIL, WATER, SALT, MONO AND DIGLYCERIDES], WATER, WHEAT FLOUR, ALMOND FLOUR, NATURAL FLAVOR), SHORTBREAD CRUMBS [WHEAT FLOUR, PALM OIL, SUGAR, INVERT SYRUP, BAKING SODA, SALT], READY GLAZE (WATER, ISOMALT, SUGAR, AGAR, POTASSIUM SORBATE, CITRIC ACID) ** contains almonds. Packaged in a container with products that contain milk** MINI TOASTED COCONUT SWIRL: FILLING (MARGARINE [PALM OIL, CANOLA OIL, WATER, SALT, MONO AND DIGLYCERIDES], SUGAR ,WATER, COCONUT FLAKES, CUSTARD POWDER [SUGAR, MODIFIED POTATO STARCH, WHEY POWDER, NON FAT DRY MILK POWDER, COCONUT OIL, CORN SYRUP, CALCIUM ALGINATE, NATURAL FLAVOR, SALT, MILK PROTEIN, SODIUM PHOSPHATE, SILICON DIOXIDE, CAROTENE (COLOR), MALT SYRUP, WHEAT FLOUR, NATURAL FLAVOR), READY GLAZE (WATER, ISOMALT, SUGAR, AGAR, POTASSIUM SORBATE, CITRIC ACID), COCOA ICING: ICING SUGAR, WATER, DRIED GLUCOSE SYRUP, COCOA POWDER.  ** Packaged in a container with products that contains almonds** MINI CHERRY CHOCOLATE CORONET; FILLING (CHERRIES, SUGAR, WATER, CORN STARCH, SODIUM CITRATE, GELLEN GUM, POTASSIUM SORBATE, NATURAL CHERRY FLAVOR), DARK CHOCOLATE SQUARES (SUGAR, COCOA LIQUOR, COCOA BUTTER, SUNFLOWER LECITHIN), READY GLAZE (WATER, ISOMALT, SUGAR, AGAR, POTASSIUM SORBATE, CITRIC ACID). ** Packaged in a container with products that contains almonds and milk** LEMON CHEESECAKE CORONET: FILLING (CHEESE FLAVOR [BUTTERMILK, CREAM, SALT, LACTIC CULTURE], SUGAR, WATER, CUSTARD POWDER [SUGAR, MODIFIED POTATO STARCH, WHEY POWDER, NON FAT DRY MILK, COCONUT OIL, WHEAT SYRUP, CALCIUM ALGINATE, NATURAL FLAVOR, TETRASODIUM DIPHOSPHATE, DISODIUM PHOSPHATE, SALT, MILK PROTEIN CONCENTRATE, MIXED CAROTENE (COLOR)], LEMON JUICE, TAPIOCA STARCH, NATURAL FLAVOR), TOPPING (SUGAR, READY GLAZE (WATER, ISOMALT, SUGAR, AGAR, POTASSIUM SORBATE, CITRIC ACID). ** Packaged in a container with products that contains almonds**)",
                            "sodium-dv": "3%",
                            "cholesterol": "10mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Assorted Danishes",
                            "trans-fat": "0g",
                            "sat-fat": "6g",
                            "total-carb-dv": "14%",
                            "dietary-fiber-dv": "0%",
                            "calories-from-fat": "99",
                            "total-fat": "11g",
                            "allergens": "Milk, Eggs, Tree Nuts, Wheat, Gluten",
                            "total-carb": "18g",
                            "sugars": "6g",
                            "protein-dv": "4%",
                            "serving-size": "1 each",
                            "total-fat-dv": " ",
                            "calories": "170",
                            "protein": "2g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0g",
                            "sodium": "70mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "All Purpose Flour (INGREDIENTS: BLEACHED WHEAT FLOUR ENRICHED (BLEACHED WHEAT FLOUR, NIACIN REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), MALTED BARLEY FLOUR.), Whole Milk (INGREDIENTS: MILK, VITAMIN D3.), Brown Sugar Light (INGREDIENTS: BROWN SUGAR (SUGAR, CANE SYRUP).), Walnut Pieces (INGREDIENTS: WALNUTS  **may contain traces of peanuts and tree nuts**), Eggs, Margarine (Trans Free) (INGREDIENTS: PALM AND PALM KERNEL OIL, SOYBEAN OIL, WATER, SALT, CONTAINS LESS THAN 2% OF NON-FAT DRY MILK SOLIDS, SOY LECITHIN, VEGETABLE MONO & DIGLYCERIDES, SODIUM BENZOATE (A PRESERVATIVE), CITRIC ACID, NATURAL & ARTIFICIAL FLAVOR, BETA CAROTENE (COLOR), VITAMIN A PALMITATE ADDED. ), Sugar, Margarine (Trans Free) (INGREDIENTS: PALM AND PALM KERNEL OIL, SOYBEAN OIL, WATER, SALT, CONTAINS LESS THAN 2% OF NON-FAT DRY MILK SOLIDS, SOY LECITHIN, VEGETABLE MONO & DIGLYCERIDES, SODIUM BENZOATE (A PRESERVATIVE), CITRIC ACID, NATURAL & ARTIFICIAL FLAVOR, BETA CAROTENE (COLOR), VITAMIN A PALMITATE ADDED. ), Salt (INGREDIENTS: SALT, SODIUM SILICOALUMINATE, DEXTROSE, POTASSIUM IODIDE AND SODIUM BICARBONATE.), Baking Powder (INGREDIENTS: SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH AND CALCIUM PHOSPHATE MONOBASIC), Cinnamon",
                            "sodium-dv": "13%",
                            "cholesterol": "37.1mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Cinnamon Crunch Walnut Bread",
                            "trans-fat": "0g",
                            "sat-fat": "3.2g",
                            "total-carb-dv": "25%",
                            "dietary-fiber-dv": "3%",
                            "calories-from-fat": "118",
                            "total-fat": "13.1g",
                            "allergens": "Milk, Eggs, Tree Nuts, Peanuts, Wheat, Gluten",
                            "total-carb": "32.3g",
                            "sugars": "18.1g",
                            "protein-dv": "9%",
                            "serving-size": "1 Slice",
                            "total-fat-dv": " ",
                            "calories": "259",
                            "protein": "4.9g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "1.2g",
                            "sodium": "293.3mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Cinnamon Roll (INGREDIENTS: ENRICHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, SUGAR, MARGARINE (PARTIALLY HYDROGENATED SOYBEAN AND COTTONSEED OIL, WATER, NONFAT MILK, CULTURED NONFAT MILK, SALT, MONO AND DIGLYCERIDES, SOY LECITHIN, VITAMIN A PALMINATE, ARTIFICIAL COLOR, ARTIFICIAL FLAVOR), SOYBEAN OIL, HIGH FRUCTOSE CORN SYRUP, YEAST, PARTIALLY HYDROGENATED SOYBEAN AND COTTONSEED OIL, CINNAMON, MONO AND DIGLYCERIDES, EGGS, SODIUM CASEINATE, MODIFIED CORN STARCH, DATEM, GLUCONO DELTA-LACTONE, BAKING SODA, SALT, SODIUM ACID PYROPHOSPHATE, MOLASSES, PROPIONIC ACID (PRESERVATIVE), ARTIFICIAL FLAVOR, ASCORBIC ACID, AZODICARBONAMIDE.)",
                            "sodium-dv": "11%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Cinnamon Rolls",
                            "trans-fat": "1.4g",
                            "sat-fat": "3.4g",
                            "total-carb-dv": "19%",
                            "dietary-fiber-dv": "4%",
                            "calories-from-fat": "62",
                            "total-fat": "6.9g",
                            "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                            "total-carb": "24.7g",
                            "sugars": "6.9g",
                            "protein-dv": "7%",
                            "serving-size": "1 each",
                            "total-fat-dv": " ",
                            "calories": "178",
                            "protein": "4.1g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "1.4g",
                            "sodium": "247mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Donut Ring (INGREDIENTS: ENRICHED WHEAT FLOUR BLEACHED (FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), VEGETABLE  SHORTENING (PALM AND/OR COTTONSEED AND/OR CANOLA OIL), WATER, SOYBEAN OIL, CONTAINS 2% OR LESS OF ALPHA TOCOPHEROL AS PRESERVATIVE, ASCORBIC ACID (AS DOUGH CONDITIONER), BETA CAROTENE (AS COLOR), CORN OIL, CORNSTARCH, DEXTROSE, EGGS, LEAVENING (BAKING SODA, SODIUM ACID PYROPHOSPHATE), MONO AND DIGLYCERIDES, NATURAL AND ARTIFICIAL FLAVORS, SALT, SODIUM STEAROYL LECTYLATE, SOY FLOUR, WHEY, YEAST.), Chocolate Icing (INGREDIENTS: SUGAR, WATER, HIGH FRUCTOSE CORN SYRUP, CORN SYRUP, PALM OIL, CORN SYRUP SOLIDS, SOYBEAN OIL, CONTAINS LESS THAN 2% OF THE FOLLOWING: COCOA, COCOA ALKALI PROCESSED, MODIFIED TAPIOCA STARCH, SOY LECITHIN, CITRIC ACID, TO PRESERVE FRESHNESS (POTASSIUM SORBATE), NATURAL AND ARTIFICIAL FLAVOR.)",
                            "sodium-dv": "11%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Donut, Chocolate Glazed",
                            "trans-fat": "0g",
                            "sat-fat": "7.1g",
                            "total-carb-dv": "19%",
                            "dietary-fiber-dv": "3%",
                            "calories-from-fat": "120",
                            "total-fat": "13.3g",
                            "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                            "total-carb": "24.5g",
                            "sugars": "4.4g",
                            "protein-dv": "7%",
                            "serving-size": "1 each",
                            "total-fat-dv": " ",
                            "calories": "237",
                            "protein": "4g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "1g",
                            "sodium": "260mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Donut Ring (INGREDIENTS: ENRICHED WHEAT FLOUR BLEACHED (FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), VEGETABLE  SHORTENING (PALM AND/OR COTTONSEED AND/OR CANOLA OIL), WATER, SOYBEAN OIL, CONTAINS 2% OR LESS OF ALPHA TOCOPHEROL AS PRESERVATIVE, ASCORBIC ACID (AS DOUGH CONDITIONER), BETA CAROTENE (AS COLOR), CORN OIL, CORNSTARCH, DEXTROSE, EGGS, LEAVENING (BAKING SODA, SODIUM ACID PYROPHOSPHATE), MONO AND DIGLYCERIDES, NATURAL AND ARTIFICIAL FLAVORS, SALT, SODIUM STEAROYL LECTYLATE, SOY FLOUR, WHEY, YEAST.)",
                            "sodium-dv": "11%",
                            "cholesterol": "0mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Donut, Glazed",
                            "trans-fat": "0g",
                            "sat-fat": "7g",
                            "total-carb-dv": "16%",
                            "dietary-fiber-dv": "3%",
                            "calories-from-fat": "117",
                            "total-fat": "13g",
                            "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                            "total-carb": "21g",
                            "sugars": "1g",
                            "protein-dv": "7%",
                            "serving-size": "1 each",
                            "total-fat-dv": " ",
                            "calories": "220",
                            "protein": "4g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "1g",
                            "sodium": "260mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Sour Cream Donut (INGREDIENTS: ENRICHED WHEAT FLOUR BLEACHED (FLOUR, NIACIN, IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), PALM AND/OR COTTONSEED AND/OR CANOLA OIL, SUGAR, DEXTROSE, SOYBEAN OIL, CONTAINS 2% OR LESS OF: ARTIFICIAL FLAVOR, BETA CAROTENE (COLOR), EGG YOLKS, ENZYMES, FOOD STARCH-MODIFIED, LEAVENING (BAKING SODA, MONOCALCIUM PHOSPHATE, SODIUM ACID,PYROPHOSPHATE), NONFAT MILK, SALT, SODIUM DIACETATE (AS PRESERVATIVE), SODIUM STEAROYL LACTYLATE, SOUR CREAM SOLIDS (CULTURED SOUR CREAM, MALTODEXTRIN, CULTURED BUTTERMILK, CULTURED SKIM MILK, WHEY, LACTIC ACID), SOY FLOUR, SOY LECITHIN, WATER, WHEAT STARCH.)",
                            "sodium-dv": "11%",
                            "cholesterol": "10mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Donut, Sour Cream",
                            "trans-fat": "0g",
                            "sat-fat": "9g",
                            "total-carb-dv": "20%",
                            "dietary-fiber-dv": "3%",
                            "calories-from-fat": "153",
                            "total-fat": "17g",
                            "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                            "total-carb": "26g",
                            "sugars": "10g",
                            "protein-dv": "5%",
                            "serving-size": "1 each",
                            "total-fat-dv": " ",
                            "calories": "270",
                            "protein": "3g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "1g",
                            "sodium": "250mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "All Purpose Flour (INGREDIENTS: BLEACHED WHEAT FLOUR ENRICHED (BLEACHED WHEAT FLOUR, NIACIN REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), MALTED BARLEY FLOUR.), Frozen Peach Slices (INGREDIENTS: PEACHES, ASCORBIC ACID AND CITRIC ACID ADDED TO RETARD OXIDATION.), Lowfat Peach Yogurt (INGREDIENTS: CULTURED PASTEURIZED GRADE A LOWFAT MILK, SUGAR, HIGH FRUCTOSE CORN SYRUP, WATER, PEACHES, MODIFIED FOOD STARCH, WHEY PROTEIN CONCENTRATE, GELATIN, NATURAL FLAVOR, CALCIUM CHLORIDE, CITRIC ACID, ANNATTO COLOR, CARMINE COLOR. ), Sugar, Salad Oil (INGREDIENTS: REFINED SOYBEAN OIL, TBHQ AND CITRIC ACID ADDED TO HELP PRESERVE FRESHNESS), Eggs, Baking Powder (INGREDIENTS: SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH AND CALCIUM PHOSPHATE MONOBASIC), Vanilla Extract (INGREDIENTS: WATER, CARAMEL COLOR, ARTIFICIAL FLAVOR, CITRIC ACID, SODIUM BENZOATE (PRESERVATIVE). ), Baking Soda (INGREDIENTS: SODIUM BICARBONATE.), Salt (INGREDIENTS: SALT, SODIUM SILICOALUMINATE, DEXTROSE, POTASSIUM IODIDE AND SODIUM BICARBONATE.)",
                            "sodium-dv": "7%",
                            "cholesterol": "22.6mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Peach Muffins",
                            "trans-fat": "0g",
                            "sat-fat": "1.1g",
                            "total-carb-dv": "21%",
                            "dietary-fiber-dv": "1%",
                            "calories-from-fat": "60",
                            "total-fat": "6.6g",
                            "allergens": "Milk, Eggs, Wheat, Gluten",
                            "total-carb": "26.8g",
                            "sugars": "9.6g",
                            "protein-dv": "6%",
                            "serving-size": "1 EA",
                            "total-fat-dv": " ",
                            "calories": "177",
                            "protein": "3.4g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0.5g",
                            "sodium": "156.1mg"
        ],
                        [
                            "sugars-dv": " ",
                            "cholesterol-dv": " ",
                            "ingredients": "Apple Cinnamon Scone (INGREDIENTS: ENRICHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, IRON,  THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), SUGAR, PALM  OIL, WATER, DICED APPLES, CINNAMON DROPS (SUGAR, PALM OIL, CINNAMON, NONFAT MILK, SOY LECITHIN), CORN SYRUP SOLIDS, MODIFIED CORN STARCH, DEXTROSE, BAKING SODA, DRIED EGG YOLK ( CONTAINS SODIUM SILICOALUMINATE), DRIED EGG WHITE ( CONTAINS CITRIC ACID), NONFAT MILK, SALT, APPLE FIBER, CINNAMON, SODIUM ALUMINUM PHOSPHATE, SOYBEAN OIL, MONOCALCIUM PHOSPHATE, WHEAT PROTEIN ISOLATE ( WHEAT GLUTEN, LACTIC ACID, SULPHITES), ASCORBIC ACID, CITRIC ACID AND ERYTHORBIC ACID (PRESERVATIVES), XANTHAN GUM, CELLULOSE GUM, MALIC ACID, MONOGLYCERIDES, ARTIFICIAL COLOR, CANOLA OIL, NATURAL AND ARTIFICIAL FLAVOR. )",
                            "sodium-dv": "7%",
                            "cholesterol": "5.3mg",
                            "trans-fat-dv": " ",
                            "serving-name": "Scone, Apple Cinnamon",
                            "trans-fat": "0g",
                            "sat-fat": "4.8g",
                            "total-carb-dv": "20%",
                            "dietary-fiber-dv": "1%",
                            "calories-from-fat": "91",
                            "total-fat": "10.1g",
                            "allergens": "Milk, Eggs, Wheat, Gluten",
                            "total-carb": "26g",
                            "sugars": "12.8g",
                            "protein-dv": "4%",
                            "serving-size": "1 each",
                            "total-fat-dv": " ",
                            "calories": "202",
                            "protein": "2.1g",
                            "sat-fat-dv": " ",
                            "dietary-fiber": "0.5g",
                            "sodium": "159.5mg"
        ]]

    
    
    
    static func getData(input: String) -> [[String:String]]? {
        if(input == "Bagels") {
            return bagels
        } else if (input == "Bakery") {
            return bakery
        }else {
            return nil
        }
    }

}
