//
//  Bolton.swift
//  UGANutrition
//
//  Created by Lakshay Sharma on 10/20/16.
//  Copyright © 2016 Lakshay Sharma. All rights reserved.
//

import Foundation

class Bolton {
    
    let bagels = [[
        "sugars-dv": " ",
        "cholesterol-dv": " ",
        "ingredients": "Everything Bagel (INGREDIENTS: UNBLEACHED WHEAT FLOUR (MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, SUGAR, CONTAINS LESS THAN 2% OR LESS OF: SESAME SEEDS, SALT, POPPY SEEDS, ONIONS, GARLIC , YEAST, MOLASSES, SOYBEAN OIL, CALCIUM PROPIONATE (MOLD INHIBITOR), PALM OIL, MONOGLYCERIDES, CORNMEAL, L-CYSTEINE, ASCORBIC ACID, ENZYMES.  **all bagels are made on shared equipment with egg and milk products**)",
        "sodium-dv": "38%",
        "cholesterol": "0mg",
        "trans-fat-dv": " ",
        "serving-name": "Bagel, Everything",
        "trans-fat": "0g",
        "sat-fat": "0.5g",
        "total-carb-dv": "53%",
        "dietary-fiber-dv": "8%",
        "calories-from-fat": "32",
        "total-fat": "3.5g",
        "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
        "total-carb": "69g",
        "sugars": "5g",
        "protein-dv": "23%",
        "serving-size": "1 each",
        "total-fat-dv": " ",
        "calories": "360",
        "protein": "13g",
        "sat-fat-dv": " ",
        "dietary-fiber": "3g",
        "sodium": "880mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "French Toast Bagel (INGREDIENTS: UNBLEACHED UNBROMATED  ENRICHED WHEAT FLOUR (MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, MAPLE BITS (SUGAR,  WHEAT FLOUR, CORN CEREAL, NATURAL FLAVOR, SOYBEAN OIL, FRUCTOSE), CONTAINS 2% OR LESS: SUGAR, SALT, YEAST, CINNAMON, CORN MEAL, NATURAL  AND ARTIFICIAL FLAVORS, CALCIUM PROPIONATE (USED AS A PRESERVATIVE), PALM OIL, MONOGLYCERIDES, DATEM, MOLASSES, SOYBEAN OIL, L-CYSTEINE, ASCORBIC ACID, ENZYMES. **all bagels are made on shared equipment with egg and milk products**)",
                    "sodium-dv": "34%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bagel, French Toast",
                    "trans-fat": "0g",
                    "sat-fat": "0.5g",
                    "total-carb-dv": "60%",
                    "dietary-fiber-dv": "8%",
                    "calories-from-fat": "18",
                    "total-fat": "2g",
                    "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                    "total-carb": "78g",
                    "sugars": "6g",
                    "protein-dv": "25%",
                    "serving-size": "1 each",
                    "total-fat-dv": " ",
                    "calories": "380",
                    "protein": "14g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "3g",
                    "sodium": "780mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Plain Bagel (INGREDIENTS: UNBLEACHED WHEAT FLOUR (MALTED BARLEY, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, SUGAR, CONTAINS 2% OF LESS OF SALT, YEAST, MOLASSES, SOYBEAN OIL, CALCIUM PROPIONATE (A MOLD INHIBITOR), PALM OIL, MONOGLYCERIDES, CORNMEAL, L-CYSTEINE, ASCORBIC ACID, ENZYMES **Produced in a facility that also processes soy, eggs, and tree nuts**products**)",
                    "sodium-dv": "29%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bagel, Plain",
                    "trans-fat": "0g",
                    "sat-fat": "0.5g",
                    "total-carb-dv": "54%",
                    "dietary-fiber-dv": "5%",
                    "calories-from-fat": "14",
                    "total-fat": "1.5g",
                    "allergens": "Milk, Eggs, Tree Nuts, Wheat, Soybeans, Gluten",
                    "total-carb": "70g",
                    "sugars": "5g",
                    "protein-dv": "23%",
                    "serving-size": "1 each",
                    "total-fat-dv": " ",
                    "calories": "340",
                    "protein": "13g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "2g",
                    "sodium": "670mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Very Berry Bagel (INGREDIENTS: UNBLEACHED UNBROMATED ENRICHED WHEAT FLOUR (MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, CONTAINS 2% OR LESS: SUGAR, SALT, CRANBERRY BITS (SUGAR, CORN SYRUP, CORN CEREAL, MODIFIED FOOD STARCH, PARTIALLY HYDROGENATED VEGETABLE OIL (COTTONSEED AND/OR SOYBEAN), CITRIC ACID, ARTIFICIAL FLAVOR, RED #40 LAKE, BLUE #1 LAKE),  CHERRY BITS (SUGAR, CORN SYRUP, CORN CEREAL, PARTIALLY HYDROGENATED VEGETABLE OIL (COTTONSEED AND/OR SOYBEAN), MODIFIED FOOD STARCH, ARTIFICIAL FLAVOR, RED #40), BLUEBERRY BITS (SUGAR, CORN FLOUR, DEXTROSE, CORN STARCH, DRIED BLUEBERRIES, BLUE #40 LAKE, RED #40 LAKE), YEAST, CORN MEAL, NATURAL AND ARTIFICIAL FLAVOR, CALCIUM PROPIONATE (USED AS A PRESERVATIVE), PALM OIL, MONOGLYCERIDES, DATEM, MOLASSES, SOYBEAN OIL, L-CYSTEINE, ASCORBIC ACID, ENZYMES, NATURAL AND ARTIFICIAL COLOR. **all bagels are made on shared equipment with egg and milk products**)",
                    "sodium-dv": "34%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bagel, Very Berry",
                    "trans-fat": "0g",
                    "sat-fat": "1g",
                    "total-carb-dv": "60%",
                    "dietary-fiber-dv": "8%",
                    "calories-from-fat": "18",
                    "total-fat": "2g",
                    "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                    "total-carb": "78g",
                    "sugars": "6g",
                    "protein-dv": "25%",
                    "serving-size": "1 each",
                    "total-fat-dv": " ",
                    "calories": "380",
                    "protein": "14g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "3g",
                    "sodium": "790mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Wheat & Oat Bagel (INGREDIENTS: UNBLEACHED WHEAT FLOUR (MALTED BARLEY FLOUR, NIACIN, REDUCE IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, OATS, WHEAT BRAN, AUGAR, SALT, YEAST, MOLASSES, SOYBEAN OIL, CALCIUM PROPIONATE (USED AS A PRESERVATIVE), PALM OIL, MONOGLYCERIDES, CORNMEAL, L-CYSTEINE, ASCORBIC ACID, ENZYMES. **all bagels are made on shared equipment with egg and milk products**)",
                    "sodium-dv": "29%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bagel, Wheat Bran And Oats",
                    "trans-fat": "0g",
                    "sat-fat": "0.5g",
                    "total-carb-dv": "58%",
                    "dietary-fiber-dv": "18%",
                    "calories-from-fat": "23",
                    "total-fat": "2.5g",
                    "allergens": "Milk, Eggs, Wheat, Soybeans, Gluten",
                    "total-carb": "75g",
                    "sugars": "3g",
                    "protein-dv": "27%",
                    "serving-size": "1 each",
                    "total-fat-dv": " ",
                    "calories": "370",
                    "protein": "15g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "7g",
                    "sodium": "670mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Cinnamon Raisin Swirl Bread (INGREDIENTS: ENRICHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, REDUCED IRON,  THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID) WATER, RAISINS, SUGAR, CINNAMON FLAKES (SUGAR, VEGETABLE OIL [PALM OIL, PALM KERNEL  OIL], CINNAMON, SOY LECITHIN), WHEAT GLUTEN, CONAINS 2% OR LESS OF EACH OF THE FOLLOWING: YEAST, SOYBEAN OIL, SALT, VITAMIN A PALMITATE, CALCIUM CARBONATE, NATURAL FLAVOR, DOUGH CONDITIONERS (CONTAINS ONE OR MORE OF  THE FOLLOWING:  SODIUM STEAROYL LACTYLATE, CALCIUM STEAROYL LACTYLATE,  MONOGLYCERIDES AND/OR DIGLYCERIDES, CALCIUM PEROXIDE, CALCIUM IODATE, DATEM, ETHOXYLATED MONO- AND DIGLYCERIDES, ENZYMES), CINNAMON, CARAMEL COLOR, CULTURED WHEAT FLOUR, VINEGAR, WHEAT STARCH, CHOLECALCIFEROL (VITAMIN D3), CALCIUM SULFATE, SOY LECITHIN, GUAR GUM,  XANTHAN GUM, ALPHA TOCOPHEROL ACETATE (VITAMIN E).)",
                    "sodium-dv": "9%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Cinnamon Raisin",
                    "trans-fat": "0g",
                    "sat-fat": "1g",
                    "total-carb-dv": "23%",
                    "dietary-fiber-dv": "3%",
                    "calories-from-fat": "27",
                    "total-fat": "3g",
                    "allergens": "Wheat, Gluten",
                    "total-carb": "30.4g",
                    "sugars": "12.2g",
                    "protein-dv": "7%",
                    "serving-size": "2 SLICE",
                    "total-fat-dv": " ",
                    "calories": "162",
                    "protein": "4.1g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "1g",
                    "sodium": "202.5mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "English Muffin (INGREDIENTS: UNBLEACHED ENRICHED FLOUR (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, YEAST, CORN MEAL, WHEAT GLUTEN, CONTAINS 2% OR LESS OF THE FOLLOWING: CORN FLOUR, SALT, HIGH FRUCTOSE CORN SYRUP, VINEGAR, SOYBEAN OIL, CALCIUM SULFATE, MONOGLYCERIDES, AMMONIUM SULFATE, ASCORBIC ACID, CORN STARCH, ENZYMES, CALCIUM PROPIONATE AND POTASSIUM SORBATE (TO RETARD SPOILAGE). )",
                    "sodium-dv": "12%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, English Muffins",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "18%",
                    "dietary-fiber-dv": "1%",
                    "calories-from-fat": "9",
                    "total-fat": "1g",
                    "allergens": "Wheat, Gluten",
                    "total-carb": "24g",
                    "sugars": "0.5g",
                    "protein-dv": "9%",
                    "serving-size": "1 EA",
                    "total-fat-dv": " ",
                    "calories": "120",
                    "protein": "5g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "0.5g",
                    "sodium": "270mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Gluten Free White Bread (INGREDIENTS: WATER, TAPIOCA STARCH, BROWN RICE FLOUR, CANOLA OIL, EGG WHITES, POTATO STARCH, MODIFIED FOOD STARCH, TAPIOCA MALTODEXTRIN, DRIED CANE SYRUP, TAPIOCA SYRUP, YEAST, GUM (XANTHAN GUM, SODIUM ALGINATE, GUAR GUM), SALT, LOCUST BEAN GUM, CULTURED CORN SYRUP SOLIDS AND CITRIC ACID (MOLD INHIBITOR) ENZYMES.)",
                    "sodium-dv": "17%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Gluten Free White",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "27%",
                    "dietary-fiber-dv": "3%",
                    "calories-from-fat": "54",
                    "total-fat": "5.9g",
                    "allergens": "Eggs",
                    "total-carb": "34.7g",
                    "sugars": "4g",
                    "protein-dv": "11%",
                    "serving-size": "2 SLICE",
                    "total-fat-dv": " ",
                    "calories": "218",
                    "protein": "5.9g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "1g",
                    "sodium": "396.5mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Gluten Free Whole Grain Bread (INGREDIENTS: WATER, TAPIOCA STARCH, BROWN RICE FLOUR, CANOLA OIL, EGG WHITES, POTATO STARCH, DRIED CANE SYRUP, TAPIOCA MALTODEXTRIN, TAPIOCA SYRUP, MODIFIED FOOD STARCH, YEAST, FLAX SEED, SUGARCANE FIBER, SALT, GUM (XANTHAN GUM), SODIUM ALGINATE, GUAR GUM), AMARANTH FLOUR, SORGHUM FLOUR, TEFF FLOUR, LOCUST BEAN GUM, CULTURED BROWN RICE, BROWN RICE, AND ENZYMES. )",
                    "sodium-dv": "19%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Gluten Free Whole Grain",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "28%",
                    "dietary-fiber-dv": "5%",
                    "calories-from-fat": "54",
                    "total-fat": "5.9g",
                    "allergens": "Eggs",
                    "total-carb": "36.7g",
                    "sugars": "4g",
                    "protein-dv": "11%",
                    "serving-size": "2 slice",
                    "total-fat-dv": " ",
                    "calories": "218",
                    "protein": "5.9g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "2g",
                    "sodium": "446.1mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "Nature's Own Honey Wheat Bread (INGREDIENTS: UNBLEACHED ENRICHED FLOUR  (WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), WATER, HONEY, SUGAR, WHEAT GLUTEN, WHOLE WHEAT FLOUR, RYE FLOUR, WHEAT BRAN, CONTAINS 2% OR LESS OF EACH OF THE FOLLOWING: YEAST, SOY FLOUR, SALT, SOYBEAN OIL, MONOGLYCERIDES, ENZYMES, ASCORBIC ACID, CULTURED WHEAT FLOUR, VINEGAR, CALCIUM SULFATE, MONOCALCIUM PHOSPHATE, SOY LECITHIN, CALCIUM CARBONATE.)",
                    "sodium-dv": "10%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Honey Wheat",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "19%",
                    "dietary-fiber-dv": "2%",
                    "calories-from-fat": "17",
                    "total-fat": "1.9g",
                    "allergens": "Wheat, Soybeans, Gluten",
                    "total-carb": "24.3g",
                    "sugars": "3.7g",
                    "protein-dv": "10%",
                    "serving-size": "2 slice",
                    "total-fat-dv": " ",
                    "calories": "131",
                    "protein": "5.6g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "0.9g",
                    "sodium": "233.7mg"
        ],
                  [
                    "sugars-dv": " ",
                    "cholesterol-dv": " ",
                    "ingredients": "100% Whole Wheat Bread (INGREDIENTS: WHOLE WHEAT FLOUR, WATER, SUGAR, WHEAT GLUTEN, YEAST, CRACKED WHEAT, CONTAINS 2% OR LESS OF EACH OF THE FOLLOWING: HONEY, MOLASSES, SALT, SOYBEAN OIL, CULTURED WHEAT FLOUR, VINEGAR, CALCIUM SULFATE, MONOGLYCERIDES, ENZYMES, ASCORBIC ACID, WHEAT STARCH, SOY LECITHIN, CALCIUM CARBONATE, MONOCALCIUM PHOSPHATE, TOPPED WITH CRACKED WHEAT. )",
                    "sodium-dv": "11%",
                    "cholesterol": "0mg",
                    "trans-fat-dv": " ",
                    "serving-name": "Bread, Whole Wheat",
                    "trans-fat": "0g",
                    "sat-fat": "0g",
                    "total-carb-dv": "21%",
                    "dietary-fiber-dv": "10%",
                    "calories-from-fat": "17",
                    "total-fat": "1.8g",
                    "allergens": "Wheat, Gluten",
                    "total-carb": "27.1g",
                    "sugars": "4.9g",
                    "protein-dv": "13%",
                    "serving-size": "2 SLICE",
                    "total-fat-dv": " ",
                    "calories": "136",
                    "protein": "7.4g",
                    "sat-fat-dv": " ",
                    "dietary-fiber": "3.7g",
                    "sodium": "246.5mg"
        ]]

}
